import type { MaterialSelection } from "../api/alchemyApi";
import type { OwnedArtifact } from "../api/artifactApi";
import type { InputMode } from "../api/chatApi";
import type { MilestoneSnapshot, RunChronicle } from "../api/chronicleApi";
import type { QuestProgress } from "../api/questApi";
import type { SceneDefinition } from "../api/sceneApi";
import type { CreateSessionInput, InventoryItem, NpcStateSnapshot, PlayerState } from "../api/sessionApi";
import type { ChatMessage } from "../components/DialoguePanel";
import type { SystemLog } from "../components/SystemLogPanel";

export type GameState = {
  sessionId: string;
  playerId: string;
  player: PlayerState;
  inventory: InventoryItem[];
  sessionLoading: boolean;
  activeSceneId: string;
  activeNpcId: string;
  inputMode: InputMode;
  scenes: SceneDefinition[];
  scenesLoading: boolean;
  npcStates: Record<string, NpcStateSnapshot>;
  quests: QuestProgress[];
  questsLoading: boolean;
  messagesByNpc: Record<string, ChatMessage[]>;
  memoriesByNpc: Record<string, string[]>;
  input: string;
  loading: boolean;
  cultivationLoading: boolean;
  breakthroughLoading: boolean;
  alchemyLoading: boolean;
  error: string;
  lastActionResult: string;
  lastIntent: string;
  lastCultivationResult: string;
  lastBreakthroughResult: string;
  lastAlchemyResult: string;
  alchemyModalOpen: boolean;
  systemLogs: SystemLog[];
  chronicles: RunChronicle[];
  chronicleLoading: boolean;
  milestones: MilestoneSnapshot[];
  milestonesTotal: number;
  milestonesLoading: boolean;
  artifacts: OwnedArtifact[];
  artifactsLoading: boolean;
};

export type GameActions = {
  initializeSession: (input?: CreateSessionInput) => Promise<void>;
  setInput: (value: string) => void;
  setInputMode: (mode: InputMode) => void;
  selectQuickPrompt: (value: string) => void;
  sendMessage: () => Promise<void>;
  resetDialogue: () => Promise<void>;
  switchScene: (sceneId: string) => Promise<void>;
  selectNpc: (npcId: string) => void;
  refreshQuests: () => Promise<void>;
  cultivate: (duration: number) => Promise<void>;
  breakthrough: () => Promise<void>;
  refineAlchemy: (recipeId: string, materials: MaterialSelection[], fireLevel: number) => Promise<void>;
  consumeItem: (itemId: string) => Promise<void>;
  openAlchemyModal: () => void;
  closeAlchemyModal: () => void;
  appendLog: (text: string) => void;
  generateChronicle: () => Promise<void>;
  refreshChronicles: () => Promise<void>;
  refreshMilestones: () => Promise<void>;
  refreshArtifacts: () => Promise<void>;
  equipArtifact: (artifactId: string) => Promise<void>;
  unequipArtifact: (artifactId: string) => Promise<void>;
};

export type GameStore = GameState & GameActions;
